name: Build/test and validate PR

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".nais/**"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/workflows/alerts.yaml"
      - ".github/dependabot.yaml"

permissions:
  contents: read
  id-token: write

jobs:
  build-pr:
    name: Build and test
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-pr.yaml@feature/nav_npm_registry
    secrets: inherit
    with:
      node_auth_token: ${{ secrets.READER_TOKEN }}
