name: Deploy application

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/manual-deploy.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/workflows/alerts.yaml"
      - ".nais/alerts-dev.yaml"
      - ".nais/alerts-prod.yaml"
      - ".github/dependabot.yaml"

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-push-image.yaml@main
    secrets: inherit

  deploy-dev:
    needs: build
    name: Deploy to dev-gcp
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}

  deploy-dev-qx:
    needs: [build, deploy-dev]
    name: Deploy to dev-gcp-qx
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-qx.yaml
      image: ${{ needs.build.outputs.image }}

  deploy-prod:
    needs: [build, deploy-dev, deploy-dev-qx]
    name: Deploy to prod-gcp
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: prod-gcp
      resource: .nais/naiserator-prod.yaml
      image: ${{ needs.build.outputs.image }}
