name: Deploy application manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - qx
env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-push-image.yaml@main
    secrets: inherit
    with:
      image-tag: snapshot
      # Kun for oasis biblioteket i 'server/package.json' mappe
      install-navikt-npm-packages: true

  deploy-dev:
    needs: build
    name: Deploy to dev-gcp
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-${{ inputs.environment }}.yaml
      image: ${{ needs.build.outputs.image }}
