name: Playwright Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".nais/**"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/manual-deploy-dev.yaml"
      - ".github/workflows/security.yaml"
      - ".github/workflows/alerts.yaml"
      - ".github/dependabot.yaml"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".nais/**"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/manual-deploy-dev.yaml"
      - ".github/workflows/security.yaml"
      - ".github/workflows/alerts.yaml"
      - ".github/dependabot.yaml"
jobs:
  playwright-test:
    name: Playwright test
    uses: navikt/mob-gha-workflows/.github/workflows/playwright.yaml@main
